version: '3.8'

services:
  sas-db:
    image: giandonatoinverso/sas-db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - sas_db_data:/var/lib/mysql
    networks:
      - sas-network

  sas-backend-server:
    image: giandonatoinverso/sas-backend-server:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - sas-db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=sas-db
      - MYSQL_PORT=3306
    networks:
      - sas-network

  sas-client:
    image: giandonatoinverso/sas-client:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://sas-backend-server:8080
    depends_on:
      - sas-backend-server
    networks:
      - sas-network

volumes:
  sas_db_data:

networks:
  sas-network:
    driver: bridge